# Generated by Django 3.1.7 on 2021-03-17 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backh', '0003_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
